package com.yogi.data.model;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.emailaddress
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    private String emailaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.emailaddress
     *
     * @return the value of customer.emailaddress
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public String getEmailaddress() {
        return emailaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.emailaddress
     *
     * @param emailaddress the value for customer.emailaddress
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }
}