package com.yogi.data.model;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_date
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer_id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_date
     *
     * @return the value of orders.order_date
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_date
     *
     * @param orderDate the value for orders.order_date
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer_id
     *
     * @return the value of orders.customer_id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer_id
     *
     * @param customerId the value for orders.customer_id
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}