package com.yogi.data.dao;

import com.yogi.data.model.CustomerPromotions;
import com.yogi.data.model.CustomerPromotionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerPromotionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int countByExample(CustomerPromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int deleteByExample(CustomerPromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int insert(CustomerPromotions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int insertSelective(CustomerPromotions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    List<CustomerPromotions> selectByExample(CustomerPromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    CustomerPromotions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByExampleSelective(@Param("record") CustomerPromotions record, @Param("example") CustomerPromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByExample(@Param("record") CustomerPromotions record, @Param("example") CustomerPromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByPrimaryKeySelective(CustomerPromotions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByPrimaryKey(CustomerPromotions record);
}