package com.yogi.data.dao;

import com.yogi.data.model.OrderLine;
import com.yogi.data.model.OrderLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int countByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int deleteByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int deleteByPrimaryKey(Integer lineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int insert(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int insertSelective(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    List<OrderLine> selectByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    OrderLine selectByPrimaryKey(Integer lineNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByExampleSelective(@Param("record") OrderLine record, @Param("example") OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByExample(@Param("record") OrderLine record, @Param("example") OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByPrimaryKeySelective(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_line
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByPrimaryKey(OrderLine record);
}