package com.yogi.data.dao;

import com.yogi.data.model.Promotions;
import com.yogi.data.model.PromotionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int countByExample(PromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int deleteByExample(PromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int insert(Promotions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int insertSelective(Promotions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    List<Promotions> selectByExample(PromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    Promotions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByExampleSelective(@Param("record") Promotions record, @Param("example") PromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByExample(@Param("record") Promotions record, @Param("example") PromotionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByPrimaryKeySelective(Promotions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions
     *
     * @mbggenerated Tue Feb 05 18:12:02 IST 2013
     */
    int updateByPrimaryKey(Promotions record);
}